-- Intentionally empty.
--
-- Demo seed data and demo/test accounts were removed from the linked Supabase
-- project. Keep this file present because supabase/config.toml references it,
-- but do not insert sample products, customers, orders, or users here.
