import { type AdminProduct } from "@/lib/partspro-repository";

export function toAdminProductDto(product: AdminProduct) {
  return {
    id: product.id,
    sku: product.sku,
    slug: product.slug,
    name: product.name,
    category: product.category,
    brand: product.brand,
    grade: product.grade,
    price: product.b2bPrice,
    retailPrice: product.retailPrice,
    costPrice: product.costPrice,
    stock: product.stockQty,
    stockStatus: product.stockStatus,
    status: product.catalogStatus,
    visual: product.visual,
    warehouse: product.warehouse,
    moq: product.moq,
    vatMode: product.vatMode,
    vatRate: product.vatRate,
    rmaDays: product.rmaDays,
    warrantyDays: product.warrantyDays,
    leadTime: product.leadTime,
    weightGram: product.weightGram,
    model: product.model ?? null,
    modelCode: product.modelCode ?? null,
    modelCodes: product.modelCodes,
    batchCode: product.batchCode ?? null,
    supplier: product.supplier ?? null,
    compatibleWith: product.compatibleWith,
    tags: product.tags,
    imagePath: product.imagePath ?? null,
    imageUrl: product.imageUrl ?? null,
    imageAlt: product.imageAlt ?? null,
    galleryImagePaths: product.galleryImagePaths,
    galleryImageUrls: product.galleryImageUrls ?? [],
    updatedAt: product.updatedAt,
    createdAt: product.createdAt,
    storefront: {
      visible: product.catalogStatus === "active",
      source: "products",
    },
  };
}
